Parameters:
  InstanceId:
    Type: String
    Description: "Your EC2 Instance ID"
  AlarmName:
    Type: String
    Description: "Something like HOSTNAME CPU Credit Balance"   
  AlarmActions:
    Type: String
    Description: "Input the ARN of your SNS topic here"
Resources:
  CPUCreditBalance:
    Type: AWS::CloudWatch::Alarm
    Properties: 
      AlarmName:
        Ref: AlarmName
      AlarmDescription: CPU Balance Is Lower Than
      MetricName: CPUCreditBalance
      Namespace: AWS/EC2
      Statistic: Average
      Dimensions:
        - Name: InstanceId
          Value: 
            Ref: InstanceId
      ComparisonOperator: LessThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Threshold: 30
      AlarmActions: 
        - Ref: AlarmActions